apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  namespace: demo
  labels:
    app: demo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
        - name: container-ca9mwq
          image: "demo-server:latest"
          ports:
            - name: grpc
              containerPort: 8082
              protocol: TCP
          imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
