apiVersion: v1
kind: Service
metadata:
  name: demo-server
  namespace: demo
  labels:
    app: demo-server
spec:
  clusterIP: None
  ports:
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: demo-server
